import { Platform } from '@prisma/client';
import type { PlatformUserConfig } from './type';

export const PLATFORM_USER_CONFIGS: Record<string, PlatformUserConfig> = {
  host1: {
    platform: Platform.TENCENT_MEETING,
    ptUserId: 'user_12345',
    ptUnionId: 'tencent_user_12345',
    displayName: '张三',
    email: 'zhangsan@company.com',
    active: true,
  },
  host2: {
    platform: Platform.TENCENT_MEETING,
    ptUserId: 'user_67890',
    ptUnionId: 'tencent_user_67890',
    displayName: '李四',
    email: 'lisi@company.com',
    active: true,
  },
  host3: {
    platform: Platform.TENCENT_MEETING,
    ptUserId: 'user_11111',
    ptUnionId: 'tencent_user_11111',
    displayName: '王五',
    email: 'wangwu@company.com',
    active: true,
  },
  host4: {
    platform: Platform.TENCENT_MEETING,
    ptUserId: 'user_22222',
    ptUnionId: 'tencent_user_22222',
    displayName: '赵六',
    email: 'zhaoliu@company.com',
    active: true,
  },
  host5: {
    platform: Platform.TENCENT_MEETING,
    ptUserId: 'user_33333',
    ptUnionId: 'tencent_user_33333',
    displayName: '钱七',
    email: 'qianqi@company.com',
    active: true,
  },
  host6: {
    platform: Platform.FEISHU,
    ptUserId: 'feishu_12345',
    ptUnionId: 'feishu_user_12345',
    displayName: '张三',
    email: 'zhangsan@company.com',
    active: true,
  },
  host7: {
    platform: Platform.FEISHU,
    ptUserId: 'feishu_67890',
    ptUnionId: 'feishu_user_67890',
    displayName: '李四',
    email: 'lisi@company.com',
    active: true,
  },
  host8: {
    platform: Platform.FEISHU,
    ptUserId: 'feishu_11111',
    ptUnionId: 'feishu_user_11111',
    displayName: '王五',
    email: 'wangwu@company.com',
    active: true,
  },
  host9: {
    platform: Platform.FEISHU,
    ptUserId: 'feishu_22222',
    ptUnionId: 'feishu_user_22222',
    displayName: '赵六',
    email: 'zhaoliu@company.com',
    active: true,
  },
  host10: {
    platform: Platform.FEISHU,
    ptUserId: 'feishu_33333',
    ptUnionId: 'feishu_user_33333',
    displayName: '钱七',
    email: 'qianqi@company.com',
    active: true,
  },
};
