import { RefundChannel, RefundStatus } from '@prisma/client';
import { RefundConfig } from './type';

export const REFUND_CONFIGS: RefundConfig[] = [
  {
    afterSaleCode: 'AS_20240125_001',
    orderIndex: 0,
    submittedAt: new Date('2024-01-25 10:00:00'),
    refundedAt: new Date('2024-01-26 15:30:00'),
    refundChannel: RefundChannel.DOUYIN,
    approvalUrl: 'https://example.com/approval/AS_20240125_001',
    creatorType: 'admin',
    refundAmount: 10000,
    refundReason: '学员因个人原因申请部分退款',
    benefitUsedDays: 10,
    applicantName: '学员A',
    status: RefundStatus.SETTLED,
    financialSettledAt: new Date('2024-01-30'),
    financialNote: '已完成退款处理',
    productCategory: '课程',
  },
  {
    afterSaleCode: 'AS_20240305_002',
    orderIndex: 3,
    submittedAt: new Date('2024-03-05 14:20:00'),
    refundedAt: new Date('2024-03-06 09:15:00'),
    refundChannel: RefundChannel.DOUYIN,
    approvalUrl: 'https://example.com/approval/AS_20240305_002',
    creatorType: 'finance',
    refundAmount: 19900,
    refundReason: '服务质量不满意，申请全额退款',
    benefitUsedDays: 4,
    applicantName: '学员D',
    status: RefundStatus.SETTLED,
    financialSettledAt: new Date('2024-03-08'),
    financialNote: '全额退款已处理',
    productCategory: '咨询',
  },
  {
    afterSaleCode: 'AS_20240315_003',
    orderIndex: 2,
    submittedAt: new Date('2024-03-15 16:30:00'),
    refundedAt: null,
    refundChannel: RefundChannel.DOUYIN,
    approvalUrl: 'https://example.com/approval/AS_20240315_003',
    creatorType: 'finance',
    refundAmount: 80000,
    refundReason: '学员搬家，无法继续学习',
    benefitUsedDays: 74,
    applicantName: '学员C',
    status: RefundStatus.PENDING,
    financialSettledAt: null,
    financialNote: null,
    productCategory: '会员',
  },
  {
    afterSaleCode: 'AS_20240220_004',
    orderIndex: 4,
    submittedAt: new Date('2024-02-20 11:45:00'),
    refundedAt: null,
    refundChannel: RefundChannel.DOUYIN,
    approvalUrl: 'https://example.com/approval/AS_20240220_004',
    creatorType: 'admin',
    refundAmount: 0,
    refundReason: '已下载资料，不符合退款条件',
    benefitUsedDays: 5,
    applicantName: '学员E',
    status: RefundStatus.SETTLED,
    financialSettledAt: new Date('2024-02-22'),
    financialNote: '退款申请被拒绝',
    productCategory: '资料',
  },
];
