ALTER TYPE "VerificationCodeType" ADD VALUE IF NOT EXISTS 'IDENTITY_CONFIRM';
ALTER TYPE "VerificationCodeType" ADD VALUE IF NOT EXISTS 'CHANGE_EMAIL';
ALTER TYPE "VerificationCodeType" ADD VALUE IF NOT EXISTS 'CHANGE_PHONE';

ALTER TABLE "verification_codes"
ADD COLUMN "attempt_count" INTEGER NOT NULL DEFAULT 0;
